version: '3.9'

services:
  db:
    image: postgres:14
    container_name: customer_example_postgres_db
    environment:
      POSTGRES_DB: customer_example
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
